### ISSUE TITLE
메인화면으로 이동(`def main_page()`)

### ISSUE THREAD

**Issue by roharon** [GnuVill-HUFS/Face_Age_Battle#10]
* 메인화면으로 이동(`def main_page()`)

  > * 입력값 : 없음
  > * 반환값 : 없음
  >
  > 단순히 render을 이용하여 `main.html` 페이지를 나타냅니다

**Comment by ChanHyeokhong** [comment]
찬혁

**Comment by SeunghyeonJeon** [comment]
승현
