### ISSUE TITLE
1인모드화면=>결과창 (`def single_result(requests)`)

### ISSUE THREAD

**Issue by roharon** [GnuVill-HUFS/Face_Age_Battle#13]
* 1인모드화면=>결과창 (`def single_result(requests)`)

  > 입력값 : 얼굴사진 1개
  >
  > 반환값 : 사진1개를 얼굴처리함수에서 가져와  나이정보, 성별 퍼센트에 대한 정보를 보낸다.
  >
  > 얼굴처리함수에는 {'image':이미지 로컬저장위치} 를 전송하여 정보를 받아와야 합니다.

**Comment by SeunghyeonJeon** [comment]
승현
