### ISSUE TITLE
시작하기 화면 구현

### ISSUE THREAD

**Issue by roharon** [GnuVill-HUFS/Face_Age_Battle#3]
메인화면 (main.html)

모드설정화면으로 가기위한 초기메인화면

필수사항 : 시작버튼 1개(모드설정 화면으로 이동을 위한 버튼)
프로젝트 이름이 들어가면 될 것 같습니다

**Comment by roharon** [comment]
노아론꺼

**Comment by varyeun** [comment]
ㅡㅡ
