### ISSUE TITLE
모드설정 화면 (mode_select.html)

### ISSUE THREAD

**Issue by roharon** [GnuVill-HUFS/Face_Age_Battle#5]
모드설정 화면 (mode_select.html)

1인모드,2인모드 선택을 할 수 있는 화면 구현

필수사항 : 1인모드, 2인모드 버튼
1인모드 : 혼자 체험하는 사람 대상으로 얼굴나이 측정.

2인모드 : 얼굴나이 측정 및 서로간의 동안대결(승자가 누군지 나오도록)

**Comment by wooyo2** [comment]
우요이!
