### ISSUE TITLE
2인모드 화면(dual_mode.html)

### ISSUE THREAD

**Issue by roharon** [GnuVill-HUFS/Face_Age_Battle#7]
2인모드 화면(dual_mode.html)

두 명의 얼굴 촬영이 가능하도록 화면 구현

필수 사항 : 2개의 촬영버튼, 얼굴실시간화면(1개만 있어도 됩니다.), 촬영한 사진을 보여주는 칸 2개, 얼굴촬영 완료버튼

**Comment by varyeun** [comment]
이렇게 하는건가욤 - 지니
